### ISSUE TITLE
Replace `requests` with `aiohttp`

### ISSUE THREAD

**Issue by eitozx** [ArjunSharda/Countey#2]
I noticed that you're using `requests` library. I **recommend** you to use `aiohttp` instead because [using a sync library in async flow can cause ***blocking***](https://docs.nextcord.dev/en/stable/faq.html#what-does-blocking-mean).

And if comfortable, then I would like to get assigned this issue :>

**Comment by ArjunSharda** [comment]
Thank you for making me aware of this! I've assigned you this issue.

**Comment by eitozx** [comment]
Will it be okay if I make the PR related to this issue after 1st October as hacktoberfest will start as well? If ya got issue I don't mind doing it right away :")

**Comment by ArjunSharda** [comment]
Sure! I understand. If it’s blocking though I will follow up and reassign
the priority.
